name: Release

on: [release]

jobs:

  PyPi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v1
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: python -m pip install --upgrade pip setuptools wheel twine
      - name: Build dist packages
        run: python setup.py sdist bdist_wheel
      - name: Upload packages
        run: python -m twine upload dist/*
        env:
          TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
